import os
import time
os.system("chmod 777 *")
print("")
print("              \033[36mosrframework\033[0m")
print("")
os.system("pip3 install osrframework")
time.sleep(2)
print("")
print("              \033[36mtraceroute\033[0m")
print("")
os.system("sudo apt-get install traceroute -y")
print("")
time.sleep(2)
print("              \033[36mhttrack\033[0m")
print("")
os.system("sudo apt-get install httrack -y")
print("")
time.sleep(2)
print("              \033[36mjoomscan\033[0m")
print("")
os.system("sudo apt-get install joomscan -y")
print("")
print("              \033[36mcolorize\033[0m")
time.sleep(2)
print("")
os.system("sudo gem install colorize")
print("")
print("              \033[36metherape\033[0m")
time.sleep(2)
print("")
os.system("sudo apt-get install etherape -y")
print("")
time.sleep(2)
print("")
print("              \033[36mgnome-terminal\033[0m")
print("")
os.system("sudo apt-get install gnome-terminal -y")
print("")
time.sleep(2)
print("")
print("              \033[36mprogress_bar\033[0m")
print("")
os.system("sudo gem install progress_bar")
print("")
time.sleep(2)
print("")
print("              \033[36mXSpear\033[0m")
print("")
os.system("sudo gem install XSpear")
print("")
time.sleep(2)
print("")
print("              \033[36mterminal-table\033[0m")
print("")
os.system("sudo gem install terminal-table")
print("")
time.sleep(2)
print("")
print("              \033[36mselenium-webdriver\033[0m")
print("")
os.system("sudo  gem install selenium-webdriver")
print("")
time.sleep(2)
print("")
print("              \033[36mphp-curl\033[0m")
print("")
os.system("sudo apt-get install php-curl -y")
time.sleep(2)
print("              \033[36mphp-xml")
print("")
os.system("sudo apt-get install php-xml -y")
time.sleep(2)
print("")
print("              \033[36mRED_HAWK\033[0m")
print("")
os.system("git clone https://github.com/Tuhinshubhra/RED_HAWK")
time.sleep(2)
os.system("mv RED_HAWK tools")
time.sleep(2)
print("")
print("              \033[36mCMSeeK\033[0m")
print("")
os.system("git clone https://github.com/Tuhinshubhra/CMSeeK")
time.sleep(2)
os.system("mv CMSeeK tools")
time.sleep(2)
os.system("chmod 777 tools/CMSeeK/*")
time.sleep(2)
print("")
print("              \033[36mCMSeeK & requirements.txt\033[0m")
print("")
os.system("pip3 install -r tools/CMSeeK/requirements.txt")
print("")
time.sleep(2)
print("              \033[36mFinalRecon\033[0m")
print("")
os.system("git clone https://github.com/thewhiteh4t/FinalRecon.git")
time.sleep(2)
os.system("mv FinalRecon tools")
time.sleep(2)
os.system("chmod 777 tools/FinalRecon/*")
time.sleep(2)
print("")
print("              \033[36mFinalRecon & requirements.txt\033[0m")
print("")
os.system("pip3 install -r tools/FinalRecon/requirements.txt")
time.sleep(2)
print("")
print("              \033[36madmin-san\033[0m")
print("")
os.system("git clone https://github.com/just4tools/admin-san.git")
time.sleep(2)
os.system("mv admin-san tools")
time.sleep(2)
os.system("chmod 777 tools/admin-san/*")
time.sleep(2)
print("")
print("              \033[36madmin-san & requirements.txt\033[0m")
print("")
os.system("pip3 install -r tools/admin-san/requirements.txt")
time.sleep(2)
print("")
time.sleep(2)
print("              \033[36mXSStrike\033[0m")
print("")
os.system("git clone https://github.com/just4tools/XSStrike.git")
time.sleep(2)
os.system("mv XSStrike tools")
time.sleep(2)
os.system("chmod 777 tools/XSStrike/*")
time.sleep(2)
print("")
print("              \033[36mXSStrike & requirements.txt\033[0m")
print("")
os.system("pip3 install -r tools/XSStrike/requirements.txt")
print("")
time.sleep(2)
os.system("pip3 install -r requirements.txt")
time.sleep(2)
print("")
print("              \033[36mBruteXSS\033[0m")
print("")
os.system("git clone https://github.com/rajeshmajumdar/BruteXSS.git")
time.sleep(2)
os.system("mv BruteXSS tools")
time.sleep(2)
os.system("chmod 777 tools/BruteXSS/*")
time.sleep(2)
print("")
print("              \033[36mBruteXSS & requirements\033[0m")
print("")
os.system("apt-get install python-tk")
print("")
time.sleep(2)
print("")
print("              \033[36mdroopescan\033[0m")
print("")
time.sleep(2)
os.system("pip install droopescan")
time.sleep(2)
print("")
print("              \033[36mdroopescan & requirements.txt\033[0m")
print("")
os.system("apt-get install python-pip")
print("")
time.sleep(2)
print("")
print("              \033[36mATSCAN\033[0m")
print("")
os.system("git clone https://github.com/AlisamTechnology/ATSCAN")
time.sleep(2)
os.system("mv ATSCAN tools")
time.sleep(2)
os.system("chmod 777 tools/ATSCAN/*")
time.sleep(2)
print("")
print("              \033[36mATSCAN & requirements.txt\033[0m")
print("")
os.system("chmod +x ./tools/ATSCAN/atscan.pl")
time.sleep(1)
os.system("chmod +x ./tools/ATSCAN/install.sh")
time.sleep(2)
os.system("./tools/ATSCAN/install.sh")
time.sleep(2)
print("")
print("              \033[36mfsociety\033[0m")
print("")
os.system("git clone https://github.com/Manisso/fsociety.git")
time.sleep(2)
os.system("mv fsociety tools")
time.sleep(2)
os.system("chmod 777 tools/fsociety/*")
time.sleep(2)
print("")
print("              \033[36mfsociety & requirements\033[0m")
print("")
time.sleep(2)
os.system("./tools/fsociety/install.sh")
time.sleep(2)
print("              \033[36mcommix\033[0m")
print("")
time.sleep(2)
os.system("git clone https://github.com/commixproject/commix.git commix")
time.sleep(2)
os.system("mv commix tools")
time.sleep(1)
os.system("chmod 777 tools/commix/*")
time.sleep(2)
print("              \033[36mbettercap\033[0m")
time.sleep(1)
os.system("apt-get install bettercap -y")